mutation ($orderFormId: ID, $text: String) {
  insertCoupon(orderFormId: $orderFormId, text: $text) {
    messages {
      couponMessages {
        code,
        status,
        text
      }
    }
  }
}